name: Build CI - Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make -C 3_Implementation
           sudo apt-get update
           sudo apt-get upgrade all
           sudo apt-get install gcc-avr binutils-avr avr-libc
    
    
   


