name: Valgrind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get update
        sudo apt-get  install valgrind
        sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev 
    
